config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'top#main'
  get 'top/main'
  resources :car_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :car_item, dependent: :destroy
    has_many :car_item_products,through: :car_items,source: :product
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :car_item
    has_one :car_item_cart,through: :car_item,source: :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
end

app/controllers/car_items_controller.rb
class CarItemsController < ApplicationController
  def new
    @car_item = CarItem.new
  end
  
  def create
  end
  
  def destroy
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    product = Product.new(name: params[:product][:name],price: params[:product][:price])
    product.save
    redirect_to root_path
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_items_helper.rb
module CarItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/car_items/new.html.erb
<%= form_for @car_item, url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
    <%= f.submit '追加' %>
<% end %>

app/views/carts/show.html.erb
<%= link_to "商品一覧に戻る", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |e| %>
<p>
    商品名:<%= e.name %>
    価格:<%= e.price %> 円
    <%= link_to "削除", product_path(e), data: {"turbo-method": :delete} %>
    <%= link_to "カートに追加する", new_car_item_path %>
</p>
<% end %>

<%= link_to "商品を追加する", new_product_path %>
<%= link_to "カート一覧を見る", top_main_path %>

app/views/products/new.html.erb
<%= form_for @product, url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
    <%= f.submit '追加' %>
<% end %>